name: push
on: [push]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
          version: v1.31

    - name: test
      run: make test

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
